[profile.default]
bytecode_hash = "none"
viaIR = false
optimizer_runs = 21_000
verbosity = 3
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
ast = true
evm_version = "cancun"
libs = ["lib"]
dynamic_test_linking = true
show_progress = true

ignored_error_codes = [
  2394, # Transient storage warning
  3860, # Initcode size too large
  5574, # Contract size too large
]

remappings = [
  "solady/src/=lib/solady/src/",
  "v4-core/src/=lib/v4-periphery/lib/v4-core/src/",
  "v4-periphery/src/=lib/v4-periphery/src/",
  "forge-std/=lib/forge-std/src",
  "solmate/=lib/solmate/",
  "core/src/=src/",
]

[lint]
exclude_lints = [
  "asm-keccak256",
  "mixed-case-variable",
  "mixed-case-function",
  "incorrect-shift",
  "screaming-snake-case-immutable",
  "erc20-unchecked-transfer",
]

[profile.default.fmt]
line_length = 100

[profile.default.invariant]
fail_on_revert = true
depth = 200
runs = 256
